#!/bin/bash

export WorkPath=`pwd`

## Root Password
for ((i = 0; i < 5; i++)); do
	PASSWD=$(whiptail --title "ubuntu System" \
		--passwordbox "Enter root password. Don't use root or sudo run it" \
		10 60 3>&1 1>&2 2>&3)
	if [ $i = "4" ]; then
		whiptail --title "Note Qitas" --msgbox "Invalid password" 10 40 0	
		exit 0
	fi

	sudo -k
	if sudo -lS &> /dev/null << EOF
$PASSWD
EOF
	then
		i=10
	else
		whiptail --title "init Ubuntu System" --msgbox "Invalid password, Pls input corrent password" \
		10 40 0	--cancel-button Exit --ok-button Retry
	fi
done

echo $PASSWD | sudo ls &> /dev/null 2>&1



OPTION=$(whiptail --title "ubuntu System" \
	--menu "$MENUSTR" 20 60 12 --cancel-button Finish --ok-button Select \
	"0"   "source init" \
	"1"   "driver init" \
	"2"   "system init" \
	"3"   "config init" \
	"4"   "server init" \
	"5"   "client init" \
	"6"   "kicad install" \
	3>&1 1>&2 2>&3)
	

if [ $OPTION = '0' ]; then
	clear
	echo -e "source init\n${Line}"
	if [ -d  $WorkPath/apt ]; then
        cd $WorkPath/apt
		chmod +x ./apt.sh
		sudo ./apt.sh 
    fi
	exit 0
elif [ $OPTION = '1' ]; then
	clear
	echo -e "driver init\n${Line}"
	exit 0	
elif [ $OPTION = '2' ]; then
	clear
	echo -e "system init\n${Line}"
	exit 0
elif [ $OPTION = "3" ]; then
	clear
	echo -e "config init\n${Line}"
	exit 0
elif [ $OPTION = '4' ]; then
	clear
	echo -e "server init\n${Line}"
	if [ -d  $WorkPath/server ]; then
        cd $WorkPath/server
		chmod +x ./server.sh
		sudo ./server.sh 
    fi
	exit 0
elif [ $OPTION = "5" ]; then
	clear
	echo -e "client init\n${Line}"
	if [ -d  $WorkPath/client ]; then
        cd $WorkPath/client
		chmod +x ./client.sh
		sudo ./client.sh 
    fi
	exit 0
elif [ $OPTION = "6" ]; then
	clear
	echo -e "kicad install\n${Line}"
	if [ -d  $WorkPath/tools ]; then
        cd $WorkPath/tools
		chmod +x ./kicad.sh
		sudo ./kicad.sh 
    	fi
	exit 0
else
	whiptail --title "ubuntu System" \
		--msgbox "Please select correct option" 10 50 0
	exit 0
fi



exit 0
