#!/bin/bash

export shellPath=`pwd`
export WorkPath=$shellPath/..

function get_git()
{
	if [ ! -d  $shellPath/download ]; then
        cd $shellPath/
		sudo mkdir download
    fi
    if [ ! -f $shellPath/download/git.tar.gz ]; then
        cd $shellPath/download
		wget -O git.tar.gz https://github.com/git/git/archive/v2.22.0-rc1.tar.gz
    fi
	if [ ! -d  $shellPath/download/git ]; then
        cd $shellPath/download
		sudo mkdir git
		sudo tar -xzvf git.tar.gz  -C git --strip-components 1 
    fi
	echo "finish download git src \n${Line}"
}

function config_git()
{
	sudo yum -y install libicu-devel patch gcc-c++ readline-devel zlib-devel libffi-devel openssl-devel 
	sudo yum -y install make autoconf automake libtool bison libxml2-devel libxslt-devel libyaml-devel 
	sudo yum -y install cpio expat-devel gettext-devel curl-devel perl-ExtUtils-CBuilder cmake pcre-devel
	if [ ! -d  $shellPath/download/git ]; then
        cd $shellPath/download/git
		make configure
		./configure --prefix=/home/git 
		make && make install
		sudo echo 'export PATH=/home/git/bin:$PATH' >> /etc/profile
		sudo export PATH="/home/git/bin:$PATH" 
		source /etc/profile
    fi
	echo "finish download git src \n${Line}"
}

function get_gitlab()
{
	if [ ! -d  $shellPath/download ]; then
        cd $shellPath/
		sudo mkdir download
    fi
    if [ ! -f $shellPath/download/gitlab.tar.gz ]; then
        cd $shellPath/download
		wget -O gitlab.tar.gz  https://github.com/gitlabhq/gitlabhq/archive/v11.11.0.tar.gz
    fi
	if [ ! -d  $shellPath/download/gitlab ]; then
        cd $shellPath/download
		sudo mkdir gitlab
		sudo tar -xzvf gitlab.tar.gz  -C gitlab --strip-components 1 
    fi
	echo "finish download gitlab src \n${Line}"
}

function gitlab_config()
{
  	sudo yum -y install -y wget curl gcc checkinstall libxml2-dev libxslt-dev sqlite3 libsqlite3-dev libcurl4-openssl-dev libreadline6-dev libc6-dev libssl-dev libmysql++-dev make build-essential zlib1g-dev libicu-dev redis-server openssh-server git-core python-dev python-pip libyaml-dev postfix
	sudo yum -y install libicu-devel mysql-devel pcre-devel
	if [-d  $shellPath/download/gitlab ]; then
		echo -e "start gitlab install \n${Line}"

	else
		sudo yum install -y curl policycoreutils-python openssh-server
		sudo systemctl enable sshd
		sudo systemctl start sshd
		sudo firewall-cmd --permanent --add-service=http
		sudo systemctl reload firewalld
		sudo yum install postfix
		sudo systemctl enable postfix
		sudo systemctl start postfix
		curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh | sudo bash
		sudo EXTERNAL_URL="https://gitlab.OS-Q.com" yum install -y gitlab-ce
  	fi
}

#get_git
#config_git
#get_gitlab
gitlab_config


echo "finish gitlab config\n${Line}"

exit 0
