#!/bin/bash

_workdir=`pwd`

make
cp $_workdir/vendor.ko /usr/local/
cp $_workdir/QITAS /etc/init.d/
chmod +x /etc/init.d/QITAS
systemctl enable QITAS
systemctl start QITAS
echo "finish installing vendor info\n${Line}"
exit 0
